### ISSUE TITLE
Limit to the number of tickers 

### ISSUE THREAD

**Issue by haricsu** [ranaroussi/fix-yahoo-finance#13]
Hey,

When I call more than 30 tickers at a time, I get this error: 
```
Traceback (most recent call last):
  File "C:/Users/hari0/PycharmProjects/practice/stock.py", line 137, in <module>
    stockRawData = web.get_data_yahoo(tickers1, start, end)
  File "C:\Python27\lib\site-packages\fix_yahoo_finance\__init__.py", line 192, in download
    data = pd.Panel(_DFS_)
  File "C:\Python27\lib\site-packages\pandas\core\panel.py", line 148, in __init__
    minor_axis=minor_axis, copy=copy, dtype=dtype)
  File "C:\Python27\lib\site-packages\pandas\core\panel.py", line 173, in _init_data
    mgr = self._init_dict(data, passed_axes, dtype=dtype)
  File "C:\Python27\lib\site-packages\pandas\core\panel.py", line 228, in _init_dict
    v = v.reindex(**d)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 2733, in reindex
    **kwargs)
  File "C:\Python27\lib\site-packages\pandas\core\generic.py", line 2515, in reindex
    fill_value, copy).__finalize__(self)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 2679, in _reindex_axes
    fill_value, limit, tolerance)
  File "C:\Python27\lib\site-packages\pandas\core\frame.py", line 2690, in _reindex_index
    allow_dups=False)
  File "C:\Python27\lib\site-packages\pandas\core\generic.py", line 2627, in _reindex_with_indexers
    copy=copy)
  File "C:\Python27\lib\site-packages\pandas\core\internals.py", line 3886, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "C:\Python27\lib\site-packages\pandas\core\indexes\base.py", line 2836, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```
Is there anyway to call all the available tickers within yahoo finance?

**Comment by ranaroussi** [comment]
The limitation derives from your ticker list and connection.

As long as these two are ok, just use the downloader like so:

```python
data = pdr.get_data_yahoo(ticker_list, start=start_date, end=end_date)
```
