### ISSUE TITLE
Problem finding certificate

### ISSUE THREAD

**Issue by Bondifrench** [ranaroussi/fix-yahoo-finance#23]
Sorry, bit of a noob here.`

## Expected Result

Using Python 3.6 from Anaconda, after having installed `fix_yahoo_finance` package 
## Actual Result

````
Traceback (most recent call last):

  File "<ipython-input-15-b609a2c5a366>", line 9, in <module>
    end="2017-06-20")

  File "C:\Users\London\Anaconda3\lib\site-packages\fix_yahoo_finance\__init__.py", line 167, in download
    actions=actions, *args, **kwargs)

  File "C:\Users\London\Anaconda3\lib\site-packages\fix_yahoo_finance\__init__.py", line 317, in download_chunk
    crumb, cookie = get_yahoo_crumb()

  File "C:\Users\London\Anaconda3\lib\site-packages\fix_yahoo_finance\__init__.py", line 54, in get_yahoo_crumb
    res = requests.get('https://finance.yahoo.com/quote/SPY/history')

  File "C:\Users\London\Anaconda3\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)

  File "C:\Users\London\Anaconda3\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)

  File "C:\Users\London\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
    r"""Sends a OPTIONS request. Returns :class:`Response` object.

  File "C:\Users\London\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
    history.insert(0, r)

  File "C:\Users\London\Anaconda3\lib\site-packages\requests\adapters.py", line 405, in send
    conn = self.get_connection(request.url, proxies)

  File "C:\Users\London\Anaconda3\lib\site-packages\requests\adapters.py", line 225, in cert_verify
    raise IOError("Could not find a suitable TLS CA certificate bundle, "

OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\London\Anaconda3\lib\site-packages\requests\cacert.pem
````

I do have a certifi package which contains the file `cacert.pem`, but the path is `C:\Users\London\Anaconda3\Lib\site-packages\certifi`

## Reproduction Steps
Using this request:
```python

from pandas_datareader import data as pdr

import datetime

import fix_yahoo_finance

aapl = pdr.get_data_yahoo('AAPL',
                          start="2014-01-01",
                          end="2017-06-20")

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.8.1"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.1"
  },
  "platform": {
    "release": "8.1",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "100020bf",
    "version": "17.0.0"
  },
  "requests": {
    "version": "2.18.1"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.21.1"
  },
  "using_pyopenssl": true
}
```

**Comment by ranaroussi** [comment]
This looks like a problem with the validation of Yahoo's SSL certificate. 

This may sound like a stupid question, but is your system clock showing the correct time? If not, this may cause the SSL validation to fail.

If this isn't the case, can you try re-installing the requests package, then run your code again?

```bash
$ pip install requests --upgrade --no-cache-dir
```

**Comment by ranaroussi** [comment]
Closing for now. Please reopen if problem persists
