### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by sachin2404** [ranaroussi/fix-yahoo-finance#63]
import fix_yahoo_finance as yf
data = yf.download("TATAMOTORS", start="2019-03-29", end="2019-04-12")
print(data)

This simple program gives me an error.
Provide the solution as soon as possible
o/p:

[                       0%                       ]
[*********************100%***********************]  1 of 1 downloaded
Traceback (most recent call last):
  File "C:\Users\Sachin\Desktop\dara.py", line 3, in <module>
    data = yf.download("TATAMOTORS", start="2019-03-29", end="2019-04-12")
  File "C:\Program Files\Python37\lib\site-packages\fix_yahoo_finance\__init__.py", line 202, in download
    'Close', 'Adj Close', 'Volume']]
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\indexing.py", line 1142, in _get_listlike_indexer
    kind=self.name)
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\indexes\multi.py", line 2127, in _convert_listlike_indexer
    _, indexer = self.reindex(keyarr, level=level)
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\indexes\multi.py", line 2216, in reindex
    keep_order=False)
  File "C:\Program Files\Python37\lib\site-packages\pandas\core\indexes\base.py", line 3512, in _join_level
    ngroups = 1 + new_lev_codes.max()
  File "C:\Program Files\Python37\lib\site-packages\numpy\core\_methods.py", line 28, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by rvic** [comment]
Experiencing similar problem with recent versions of pandas. Which version of pandas and pandas_datareader are you using?

**Comment by sachin2404** [comment]
I'm using pandas with 0.24.2 and pandas_datareader with 0.7.0.
Tell me than the version which is used for fetching data.

**Comment by beyhangl** [comment]
I'm facing with same problem. 
It was working before. Might be because of yahoo servers.
