### ISSUE TITLE
DataFrame constructor not properly called

### ISSUE THREAD

**Issue by lewisdawson** [ranaroussi/fix-yahoo-finance#65]
When using Python 3.5.6, Pandas 23.4, and fix-yahoo-finance 0.1.28, I get the error below. 

```
Traceback (most recent call last):
  File "/yahoo/yahoo_data_fetcher.py", line 9, in <module>
    data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-06-15")
  File "/lib/python3.5/site-packages/fix_yahoo_finance/__init__.py", line 350, in download
    actions=actions, auto_adjust=auto_adjust)
  File "/lib/python3.5/site-packages/fix_yahoo_finance/__init__.py", line 290, in _download_one
    actions=actions, auto_adjust=auto_adjust)
  File "/lib/python3.5/site-packages/fix_yahoo_finance/__init__.py", line 247, in history
    dividends, splits = self._parse_actions(data["chart"]["result"][0])
  File "/lib/python3.5/site-packages/fix_yahoo_finance/__init__.py", line 127, in _parse_actions
    dividends = _pd.DataFrame(data["events"]["dividends"].values())
  File "/lib/python3.5/site-packages/pandas/core/frame.py", line 422, in __init__
    raise ValueError('DataFrame constructor not properly called!')
ValueError: DataFrame constructor not properly called!
```

I was able to fix it locally by wrapping the values dict's in `_parse_actions()` in a list:

```
if "events" in data:
            if "dividends" in data["events"]:
                dividends = _pd.DataFrame(list(data["events"]["dividends"].values()))    # <-- Here
                dividends.set_index("date", inplace=True)
                dividends.index = _pd.to_datetime(dividends.index, unit="s")
                dividends.sort_index(inplace=True)
                dividends.columns = ["Dividends"]

            if "splits" in data["events"]:
                splits = _pd.DataFrame(list(data["events"]["splits"].values()))    # <-- Here
                splits.set_index("date", inplace=True)
                splits.index = _pd.to_datetime(
                    splits.index, unit="s")
                splits.sort_index(inplace=True)
                splits["Stock Splits"] = splits["numerator"] / \
                    splits["denominator"]
                splits = splits["Stock Splits"]
```

**Comment by ranaroussi** [comment]
Thanks! Your solution was dded to v 0.1.29 :)
